-- CRIAÇÃO DO BANCO DE DADOS DA PIZZARIA
CREATE DATABASE PIZZARIA

-- SELECIONA O BD
USE PIZZARIA

-- CRIAÇÃO DA TABELA CLIENTES
-- A TABELA CLIENTES NÃO ESTÁ PRESENTE NOS SCRIPTS DE CADASTRAR PIZZAS
CREATE TABLE CLIENTES (
    USUARIO_ID  INT IDENTITY(1,1) NOT NULL, -- IDENTITY (1,1) INICIA NO 1 E ADICIONA 1 A CADA LINHA, ASSIM GERANDO ID'S CRESCENTES
    EMAIL       VARCHAR(50) UNIQUE NOT NULL, -- UNIQUE POIS SÓ VAI PODER HAVER 1 USUÁRIO COM ESTE E-MAIL
    USUARIO     VARCHAR(100) NOT NULL,
    SENHA       VARCHAR(30) NOT NULL, -- SENHA EM ATÉ 30 POR QUE É O LOGIN DE UMA PIZZARIA, NÃO DE UM BANCO E O BD AGRADECE
    CPF         VARCHAR(11) NOT NULL,
    TELEFONE    VARCHAR(15) NOT NULL, -- EXEMPLO: (11)99999-9999

    CONSTRAINT PK_USUARIO_ID PRIMARY KEY(USUARIO_ID)
)

-- ADICIONANDO UM REGISTRO PARA TESTES
INSERT INTO CLIENTES VALUES (
    'henrique@gmail.com',
    'Henrique Cordeiro de Oliveira',
    '0',
    '11111111111',
    '(11)99999-9999'
)


-- CRIAÇÃO DA TABELA PIZZA

CREATE TABLE PIZZA (
    PIZZA_ID     INT IDENTITY(1,1) NOT NULL, -- INICIA NO 1 E ADICIONA MAIS 1 A CADA LINHA
    PIZZA        VARCHAR(40), -- EXEMPLO: CALABRESA, MUSSARELA
    INGREDIENTES VARCHAR(255), -- "Molho de tomate, queijo, pepperoni e azeitonas." -- exemplo do site
    PRECO        DECIMAL(5,2) NOT NULL,
    IMAGEM_URL   VARCHAR(255)

    CONSTRAINT PK_PIZZA_ID PRIMARY KEY(PIZZA_ID)
)

SELECT *
FROM PIZZA
